import type { Metadata } from "next";
import "./globals.css";
import { inter, robotoMono } from "@/app/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={cn(
          "antialiased",
          inter.variable,
          robotoMono.variable,
          inter.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
